Add controllers
v01cecrack/java-shareit pull request #1
Opened 2023-07-02 09:35 UTC by v01cecrack

2023-07-02 12:36 UTC, NikolaiDem requested changes

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/error/ConflictException.java
> +public class ConflictException extends RuntimeException {
Лучше добавить конструктор с описанием исключения и его причиной:

    public ConflictException(String message, Throwable cause) {
        super(message, cause);
    }

Аналогично для остальных исключений

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage(), "Validation error");
Все исключения еще лучше и залогировать
log.error(...)

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage(), "Validation error");
Все описания, например, "Validation error" лучше получать из самого объекта исключения

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto addItem(@Valid @RequestBody ItemDto itemDto, @RequestHeader("X-Sharer-User-Id") Integer id) {
"X-Sharer-User-Id" лучше вынести в константу

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemDao.java
> +    public ItemDto createItem(ItemDto itemDto, User user) {
Лучше не смешивать объекты dto и доменные, вместо itemDto использовать item.
Аналогично для остальных методов

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemDao.java
> +        itemMap.remove(item.getId());
Удалять необязательно, следующий метод put сделает успешную замену объекта )

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        itemDto.setId(++id);
Генерацию id лучше вынести в репозиторий, чтобы сервис не менялся при изменении типа репозитория

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        User user = userDao.getUserMap().get(userId);
Обращаться к внутренней реализации репозитория (getUserMap()) не нужно. Лучше вызвать метод userDao.getById(...)
Аналогично для validateItem

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(item -> ItemMapper.toItemDto(item))
Можно через ссылку на метод
                .map(ItemMapper::toItemDto)

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .map(item -> ItemMapper.toItemDto(item))
Можно проще
                .map(ItemMapper::toItemDto)

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if ((itemDto.getAvailable() == false)) {
Можно проще:
if (!itemDto.getAvailable()) { ...

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    @NotNull
Если есть NotEmpty, то NotNull избыточно

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +@Service
Класс можно не делать бином, потому что все его методы статические

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/User.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/User.java
> +    @NotNull
Аннотации валидации здесь не нужны

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    private final ItemService itemService;
Добавить логирование всех входящих запросов

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserController.java
>  public class UserController {
Добавить логирование всех входящих запросов

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserDao.java
> +@Data
Аннотация лишняя

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserDao.java
> +        userMap.remove(userId);
Удалять необязательно, следующий метод put сделает успешную замену объекта )

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        userDto.setId(++id);
Генерацию id лучше вынести в репозиторий, чтобы сервис не менялся при изменении типа репозитория

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            if (user.getEmail().contains(userDto.getEmail())) {
Почему contains? Достаточно только частичного совпадения email-ов?

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Data
Лучше не использовать вместе аннотации, по которым генерятся одинаковые структуры (в данном случае конструкторы), чтобы не возникало потенциальных конфликтов. Поэтому, если нужен билдер, то вместо @Data можно отдельно вытащить геттеры, сеттеры и что еще необходимо.

2023-07-02 12:36 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotNull
ЛУчше NotBlank

2023-07-03 13:27 UTC, v01cecrack commented on src/main/java/ru/practicum/shareit/item/ItemDao.java
> +    public ItemDto createItem(ItemDto itemDto, User user) {
Не понял что надо переделать, в параметрах к методам на этом слое нужны itemы, и на верхнем слое тогда itemDto в item смаппить?

2023-07-03 13:31 UTC, v01cecrack commented on src/main/java/ru/practicum/shareit/error/ConflictException.java
> +public class ConflictException extends RuntimeException {
Сделал конструктор, но без причины, так как не понимаю что передавать во второй параметр при создании обьекта, если не использовать трай кеч, вот например:
if ((!itemDto.getAvailable())) {
            throw new NotAvailableException("Not available item", ????????);
        }

2023-07-03 22:59 UTC, NikolaiDem requested changes

2023-07-03 22:59 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +        return new ErrorResponse(e.getMessage(), e.getMessage());
Второй аргумент выглядит лишним, так как дублирует первый.
Аналогично для остальных методов

2023-07-03 22:59 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +        log.error("Validation error");
При логировании лучше записывать детали исключения.
Аналогично для остальных методов

2023-07-03 22:59 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemDao.java
> +    public ItemDto createItem(ItemDto itemDto, User user) {
Да

2023-07-03 22:59 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                .filter(item -> item.getOwner().getId() == userId)
Лучше отфильтровать items на уровне репозитория. Можно в нем создать метод getByOwnerId(...)

2023-07-03 22:59 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +            if (user.getEmail().contains(userDto.getEmail()) && user.getId() != userId) {
Почему contains?

2023-07-24 22:16 UTC, merged