tz 15
v01cecrack/java-shareit pull request #3
Opened 2023-08-05 20:16 UTC by v01cecrack

2023-08-06 23:54 UTC, NikolaiDem requested changes

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
>  @Service
Необходимо сделать сервис транзакционным.
Аналогично для остальных сервисов

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemController.java
>  /**
И @Validated

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (itemDto.getRequestId() > 0) {
С Optional хорошей практикой является применение chain стиля:
        if (itemDto.getRequestId() > 0) {
            itemRequestRepository.findById(itemDto.getRequestId())
                    .ifPresentOrElse(item::setRequest, () -> {
                        throw new ObjectNotFoundException("Такого запроса не существует!");
                    });
        }

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (from < 0) {
Валидация уже есть в контроллере

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapper.java
> +//                .request()
Удалить лишние комментарии

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
>  public class ItemRequestController {
@Validated

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestRepository.java
> +@Repository
Для интерфейса аннотация не нужна

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        if (itemRequestDto.getDescription() == null || itemRequestDto.getDescription().isEmpty()) {
Валидацию лучше добавить в контроллер

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        if (userOptional.isEmpty()) {
Проверку isEmpty и get лучше объединить в одну цепочку

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            for (Item item : itemList) {
Вместо вложенного цикла лучше использовать мапу. В качестве ключа - requestId или request, а значения - список item-ов

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +        if (from < 0) {
Валидацию лучше добавить в контроллер

2023-08-06 23:54 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/item/dao/ItemRepository.java
> +    Page<Item> search(String text, Pageable pageable);
Добавить тест дял метода

2023-08-08 14:27 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            for (Item item : itemList) {
Не исправлено

2023-08-08 23:35 UTC, NikolaiDem requested changes

2023-08-08 23:35 UTC, NikolaiDem commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            ItemRequestResponseDto dto = resultMap.keySet().stream()
Использование стрима в цикле все равно содержит квадратичную сложность

2023-08-10 14:16 UTC, v01cecrack commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            ItemRequestResponseDto dto = resultMap.keySet().stream()
Я не знаю как сделать без квадратичной сложности, если я буду использовать мапу. В качестве ключа - requestId или request, а значения - список item-ов, то у меня на каждый реквестАйди будет по одному итему максимум, ведь ключи уникальны, и каждый итем будет перезаписывать предыдущий в мапе, а итемов может быть нескольно, так что я не понимаю как это сделать(

2023-08-12 06:20 UTC, NikolaiDem approved these changes

2023-08-18 14:52 UTC, merged